version: '3.7'

services:
  db:
    image: mysql:5.7 
    # 何のコマンド？
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci 
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample
      MYSQL_PASSWORD: password
    ports:
      - 4306:3306
    volumes:
      - mysql-db:/var/lib/mysql
  
  api:
    tty: true
    depends_on:
      - db
    build:
      context: ./api
      dockerfile: Dockerfile
      # image: "test_api:1.0"
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
    command: rails server -b 0.0.0.0
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
      # image: "test_front:1.0"
    volumes:
      - ./front/app:/usr/src/app
    command: 'yarn dev'
    ports:
      - 8000:3000
volumes:
  mysql-db:
    driver: local


